## helper functions for constructing SPM calls used by targets ----

# smooth ALL the TRs, including the soon-to-be-discarded ones
# so that this timeseries stays as long as the regular unsmoothed BOLD
spm_smooth <- function (bold_path, n_trs, kernel = 4, script = matlab_spmbatch_smooth) {
  out_prefix <- glue("smoothed_{kernel}mm_")
  out_path <- file.path(dirname(bold_path), paste0(out_prefix, basename(bold_path)))
  
  matlab_commands = c(
    rvec_to_matlabcell(paste(bold_path, 
                             1:n_trs, 
                             sep = ","),
                       matname = "paths_nifti"),
    assign_variable("out_prefix", out_prefix),
    assign_variable("kernel", kernel),
    call_script(script)
  )
  
  with_path(
    matlab_path, # assume this is a global variable that will be instantiated in the targets script
    run_matlab_code(matlab_commands)
  )
  
  return (out_path)
}

spm_spec_est_level1 <- function (model_path,
                                 tr_duration,
                                 trs_to_use,
                                 bolds,
                                 events_prespm, 
                                 confounds_prespm,
                                 script = matlab_spmbatch_spec_est_level1,
                                 basis = "canonical") {
  
  dir.create(here::here(model_path), showWarnings = FALSE)
  out_path <- here::here(model_path, "SPM.mat")
  # ALWAYS DELETE THE EXISTING SPM.mat BEFORE RE-RUNNING
  # bc SPM does not offer an overwrite setting and will error out if SPM.mat exists in the specified directory
  if (file.exists(out_path)) file.remove(out_path)
  
  matlab_commands = c(
    assign_variable("out_path", dirname(out_path)),
    assign_variable("tr_duration", tr_duration),
    rvec_to_matlabcell(bolds,
                       matname = "paths_nifti"),
    rvec_to_matlab(trs_to_use,
                   matname = "trs_to_use"),
    rvec_to_matlabcell(events_prespm,
                       matname = "paths_onsets"),
    rvec_to_matlabcell(confounds_prespm,
                       matname = "paths_confounds"),
    assign_variable("basis", basis),
    # contrasts are not set by this script anymore! 
    # they are handled in matlab with the SPM.mat generated by this script
    call_script(script)
  )
  
  with_path(
    matlab_path,
    run_matlab_code(matlab_commands)
  )
  
  return (out_path)
}

spm_spec_est_level2 <- function (model_path,
                                 cons,
                                 con_name,
                                 script = matlab_spmbatch_spec_est_level2) {
  
  dir.create(here::here(model_path), showWarnings = FALSE)
  out_path <- here::here(model_path, "SPM.mat")
  if (file.exists(out_path)) file.remove(out_path)
  
  matlab_commands = c(
    assign_variable("out_path", dirname(out_path)),
    # to set as the name inside SPM Contrast Manager (for the edification of future SPM GUI users)
    assign_variable("contrast_name", con_name),
    rvec_to_matlabcell(cons,
                       matname = "paths_con"),
    # contrasts are not set by this script anymore! 
    # they are handled in matlab with the SPM.mat generated by this script
    call_script(script)
  )
  
  with_path(
    matlab_path,
    run_matlab_code(matlab_commands)
  )
  
  return (out_path)
}

spm_voi <- function (model_path, script = matlab_spmbatch_voi) {
  out_path <- model_path %>% 
    dirname() %>% 
    file.path("VOI_sc_1.mat")
  
  matlab_commands <- c(
    assign_variable("model_path", model_path),
    call_script(script)
  )
  
  with_path(
    matlab_path,
    run_matlab_code(matlab_commands)
  )
  
  return (out_path)
}